### PR TITLE
Replace in-source googletest with external googletest setup

### PR DESCRIPTION
**Pull request by scheibel**
This PR removes the in-source googletest release and relies on an external source tree of googletest.
The project would then be integrated into the own cmake build tree for testing.

On Ubuntu systems, the sources can be installed using
```shell
apt install googletest
```
which is available since Ubuntu 18.04.
As general solution, the environment variable `googletest_DIR` is used to search for the sources.

Open issues / questions:
* Provide an easy way to download the latest googletest sources (a git submodule?).

### CODE REVIEW

**Comment by sbusch42** [comment]
I remember that when we first decided to include googletest directly in cmake-init, it was generally advised not to use any pre-built versions of gtest/gmock, because the compiler settings have to match those of the project it is included in exactly. Therefore, it was advised to always compile gtest/gmock with the project itself. Has this policy changed since then?

**Comment by scheibel** [comment]
I'm not sure if the policy changed but this PR uses a gmock integration where it is compiled in the context of the own project (by means of compiler). No pre-built version of gmock and gtest is used.

However, I need to check if we need to pass additional compiler or linker flags to gmock/gtest that are specified in the own project. I'm currently unaware of compiler settings that would affect ABI changes.

**Comment by sbusch42** [comment]
We should add the info you gave above (how to install the sources and the environment variable) to the documentation and possible to the error message as well. I'm not sure about the external project, in my experience that is not nice to handle, so I would rather leave it like this, especially if installing the source is so easy as to install a package on ubuntu.

**Comment by sbusch42** [comment]
:shipit:

**Comment by Tachi107** [comment]
> it was advised to always compile gtest/gmock with the project itself. Has this policy changed since then?

Yes, that seems to have changed. They removed that guideline from their FAQ in https://github.com/google/googletest/commit/5437926b2213b1c45c2f34bd858734de90e5fffd, and now they even suggest using `pkg-config`, see [here](https://google.github.io/googletest/pkgconfig.html)

**Comment by scheibel** [comment]
I changed the approach to the one suggested by @Tachi107. Thanks for the links.
On my ubuntu machine, I installed `libgmock-dev` that comes with all required files.
On macOS, the required googletest package is provided by homebrew under the name `googletest`.

**Pull request merged**
